### ISSUE TITLE
Screen size should not be hardcoded in clients

### ISSUE THREAD

**Issue by miguems** [dsi-icl/ove#2]
https://github.com/dsi-icl/ove/blob/8cf106fda1bc3d7472bdf52eb846fc66de863b80/packages/ove-app-maps/src/client/view/Maps.js#L17 and following lines

**Comment by senakafdo** [comment]
This is hardcoded only for the moment. We should get the total height/width from OVE based on the dimensions of a section. Previously, the GDO framework made calculations based on number of nodes covered. Currently, we can work with number of pixels covered. However, the way we decide to do the layouts is yet to be decided, and I plan to discuss this today afternoon.

**Comment by senakafdo** [comment]
Please note that d7439fc is an invalid commit, and this issue is not yet fixed.

**Comment by senakafdo** [comment]
Fixed in 3c2a38b.
