### ISSUE TITLE
Consistency in formats for json entries

### ISSUE THREAD

**Issue by miguems** [dsi-icl/ove#3]
https://github.com/dsi-icl/ove/blob/8cf106fda1bc3d7472bdf52eb846fc66de863b80/packages/ove-app-images/src/config.json#L48

Lines 48, 49, 100, 101 do not have quotes as other entries do (L22,23,74,75...).

Which would be the preferred format?

**Comment by senakafdo** [comment]
Resolved in 7c9d26e.
