### ISSUE TITLE
tileOverlap property on OSD configuration

### ISSUE THREAD

**Issue by miguems** [dsi-icl/ove#4]
https://github.com/dsi-icl/ove/blob/8cf106fda1bc3d7472bdf52eb846fc66de863b80/packages/ove-app-images/src/config.json#L97

This one uses property "tileOverlap", rest of entries use "overlap". Which one is preferred?

Also, related, http://benvanik.tumblr.com/post/13978156533/tile-overlap suggests to always use 1px instead of 0px.

**Comment by senakafdo** [comment]
Resolved in 7c9d26e.
