### ISSUE TITLE
OVE multiple iframe issue

### ISSUE THREAD

**Issue by oserban** [dsi-icl/ove#55]
Sometimes OVE creates multiple iframes, some of them transparent. The transparent ones do not display any content, but it may block the proper rendering the other components.

**Comment by senakafdo** [comment]
@oserban, need some help here. Would you be able to provide instructions on how to consistently reproduce this issue? That way it will be easy to isolate the issue and test the fix.

**Comment by senakafdo** [comment]
I have reproduced this issue, consistently. The steps are actually pretty straightforward. You need to create many sections, and then relaunch the browsers without refreshing the controller. This is automatically fixed when all sections are deleted and recreated, which has been typical for most tests.

**Comment by senakafdo** [comment]
The actual issue is as follows. When ever a new client joins, it sends a read request and in return OVE core responds with a create and an update. I believe that we need to stop doing the create if an iframe already exists and that should fix this issue - the update is what we want.
