### ISSUE TITLE
Code review for ove-app-html

### ISSUE THREAD

**Issue by jamesscottbrown** [dsi-icl/ove#65]
As a general comment, there are lots of things defined using ``let`` that never change value so could be defined as ``const``.

1. In [``updateURL``](https://github.com/dsi-icl/ove/blob/829c63a9ee5f11dec3fa88fedb2022c1fd607993/packages/ove-app-html/src/client/common/html.js#L9) it would be clearer to treat ``changeAt`` like ``launchDelay`` and define

````JavaScript
const timeUntilChange = (state.changeAt || new Date().getTime()) - new Date().getTime();
````

then use this as the argument to ``setTimeout``. 

As a further improvement, you could give the anonymous function as a name so that:

````Javascript

    setTimeout(function () {
        if (launchDelay > 0) {
            setTimeout(function () {
                $('.html-frame').show();
            // helps browsers pre-load content before displaying page
            }, launchDelay);
        }
        $('.html-frame').attr('src', state.url);
        // helps browsers load content precisely at the same time
}, (state.changeAt || new Date().getTime()) - new Date().getTime());
````

becomes

````JavaScript

let showAfterDelay = function () {
        if (launchDelay > 0) {
            setTimeout(function () {
                $('.html-frame').show();
            // helps browsers pre-load content before displaying page
            }, launchDelay);

        $('.html-frame').attr('src', state.url);
};

const timeUntilChange = (state.changeAt || new Date().getTime()) - new Date().getTime();
setTimeout(showAfterDelay, timeUntilChange);
````

2. The [long line](https://github.com/dsi-icl/ove/blob/829c63a9ee5f11dec3fa88fedb2022c1fd607993/packages/ove-app-html/src/client/control/html.js#L7) 

````Javascript
 window.ove.state.current.launchDelay =
parseInt(new URLSearchParams(location.search.slice(1)).get('launchDelay') || 0);
````

could be two shorter, syntactically simpler lines 

````JavaScript
        const launchDelay = new URLSearchParams(location.search.slice(1)).get('launchDelay');
        window.ove.state.current.launchDelay = parseInt(launchDelay || 0);
````

3. [``appId == 'html'``](https://github.com/dsi-icl/ove/blob/829c63a9ee5f11dec3fa88fedb2022c1fd607993/packages/ove-app-html/src/client/view/html.js#L4) should be ``appId === 'html'``

**Comment by senakafdo** [comment]
@jamesscottbrown, agree with all except the change to:
```JS
window.ove.state.current.launchDelay =
parseInt(new URLSearchParams(location.search.slice(1)).get('launchDelay') || 0);
```
There is really no reason to extract the intermediate result into a variable if it is just the parseInt method that would be using it or the default. A better solution may be to have some common utilities defined, one of which could be a method to fetch a URL search param.
