### ISSUE TITLE
Code review for over-app-images

### ISSUE THREAD

**Issue by jamesscottbrown** [dsi-icl/ove#66]
1. There are two instances of ``var`` in [``setPosition``](https://github.com/dsi-icl/ove/blob/829c63a9ee5f11dec3fa88fedb2022c1fd607993/packages/ove-app-images/src/client/view/images.js#L31) that could be ``const``

2. [``loadOSD``](https://github.com/dsi-icl/ove/blob/829c63a9ee5f11dec3fa88fedb2022c1fd607993/packages/ove-app-images/src/client/common/images.js#L11) has an unused argument ``reject``

3. [``sendViewportDetails``](https://github.com/dsi-icl/ove/blob/829c63a9ee5f11dec3fa88fedb2022c1fd607993/packages/ove-app-images/src/client/control/images.js#L28) has an unused argument ``viewer``

4. You multiply by ``1.0`` "for float division" in [``initControl``](https://github.com/dsi-icl/ove/blob/829c63a9ee5f11dec3fa88fedb2022c1fd607993/packages/ove-app-images/src/client/control/images.js#L12) and [``setPosition``](https://github.com/dsi-icl/ove/blob/829c63a9ee5f11dec3fa88fedb2022c1fd607993/packages/ove-app-images/src/client/view/images.js#L40), but this is unnecessary: in JavaScript [there is no specific type for integers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type), so ``typeof(parseInt(2))`` is ``"number"`` and  ``parseInt(2) / parseInt(4)`` is ``0.5``.

5. [``appId == 'images'``](https://github.com/dsi-icl/ove/blob/829c63a9ee5f11dec3fa88fedb2022c1fd607993/packages/ove-app-images/src/client/view/images.js#L4) should use ``===`` rather than ``==``

6. [``Object.keys(l).length != 0``](https://github.com/dsi-icl/ove/blob/829c63a9ee5f11dec3fa88fedb2022c1fd607993/packages/ove-app-images/src/client/view/images.js#L35) should use ``!==`` rather than ``!=``

**Comment by senakafdo** [comment]
Note to self: need to handle all promise rejections properly.
