### ISSUE TITLE
OVE documentation

### ISSUE THREAD

**Issue by davidbirchwork** [dsi-icl/ove#7]
Suggest using http://apidocjs.com/#getting-started to self document the API's for the apps and core 

(a note for ove v0.2)

**Comment by senakafdo** [comment]
We also need to include the following documentation:
- A design/architecture document
- A user guide
- An application developer guide

**Comment by miguems** [comment]
Have there been any discussions on creating a user manual for each app/package? Maybe a good idea to also have a template for those.

**Comment by senakafdo** [comment]
@miguems, we did not discuss on apps as yet. Fully agree that those need to be documented as well.

**Comment by davidbirchwork** [comment]
Suggest we use API documentation compatible with https://swagger.io/ 
For .net API's https://github.com/domaindrivendev/Swashbuckle.AspNetCore will generate compatible doc and HTML viewers directly from code doc.

**Comment by senakafdo** [comment]
All OVE core and OVE apps APIs are now documented using Swagger. To find an interactive listing of the APIs visit, `http://{URL}/api-docs/` (works for OVE core and each app).
