### ISSUE TITLE
GDO equivalent config for DODEV 

### ISSUE THREAD

**Issue by davidbirchwork** [dsi-icl/ove#8]
To modify config to enable DODEV to load GDO sized content in two halves - left and right & implement switch buttons for testing

**Comment by davidbirchwork** [comment]
reopening as corresponding switch buttons not implemented yet @davidbirchwork to complete

**Comment by senakafdo** [comment]
@davidbirchwork, correct that the switch buttons are not implemented, but isn't that an enhancement to DSI AV? The issue in OVE is fixed, :-).

**Comment by davidbirchwork** [comment]
Confirmed this is now functional in DODEV space
